name = "redirect-worker"
main = "src/index.js" # 指定入口文件
compatibility_date = "2025-05-08"

# 生产配置环境
[env.production]
kv_namespaces = [
  { binding = "REDIRECT_ROUTES", id = "YOUR_PRO_KV_ID" }
]
routes = [
  { pattern = "s.niu.one/*", zone_name = "s.niu.one" }
]

# 开发环境配置
[env.development]
kv_namespaces = [
  { binding = "REDIRECT_ROUTES", id = "YOUR_DEV_KV_ID" }
]
